// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rediscluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	NodesPerShard int32                  `protobuf:"varint,3,opt,name=nodes_per_shard,json=nodesPerShard,proto3" json:"nodes_per_shard,omitempty"`
	RedisPort     uint32                 `protobuf:"varint,4,opt,name=redis_port,json=redisPort,proto3" json:"redis_port,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *CreateClusterRequest) GetNodesPerShard() int32 {
	if x != nil {
		return x.NodesPerShard
	}
	return 0
}

func (x *CreateClusterRequest) GetRedisPort() uint32 {
	if x != nil {
		return x.RedisPort
	}
	return 0
}

func (x *CreateClusterRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterResponse) Reset() {
	*x = CreateClusterResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterResponse) ProtoMessage() {}

func (x *CreateClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClusterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"` // "CreatingPods" | "PodsReady" | "Meeting" | "AllocatingSlots" | "Ready"
	Completed     int32                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProgress) Reset() {
	*x = CreateProgress{}
	mi := &file_proto_rediscluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProgress) ProtoMessage() {}

func (x *CreateProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProgress.ProtoReflect.Descriptor instead.
func (*CreateProgress) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *CreateProgress) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *CreateProgress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	MasterCount   int32                  `protobuf:"varint,3,opt,name=master_count,json=masterCount,proto3" json:"master_count,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	SlotBalance   string                 `protobuf:"bytes,5,opt,name=slot_balance,json=slotBalance,proto3" json:"slot_balance,omitempty"`
	Nodes         []*NodeInfo            `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStatusResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GetStatusResponse) GetMasterCount() int32 {
	if x != nil {
		return x.MasterCount
	}
	return 0
}

func (x *GetStatusResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *GetStatusResponse) GetSlotBalance() string {
	if x != nil {
		return x.SlotBalance
	}
	return ""
}

func (x *GetStatusResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MasterId      string                 `protobuf:"bytes,5,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Slots         []string               `protobuf:"bytes,6,rep,name=slots,proto3" json:"slots,omitempty"`
	Healthy       bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_rediscluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeInfo) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *NodeInfo) GetSlots() []string {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *NodeInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ScaleClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleClusterRequest) Reset() {
	*x = ScaleClusterRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleClusterRequest) ProtoMessage() {}

func (x *ScaleClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleClusterRequest.ProtoReflect.Descriptor instead.
func (*ScaleClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{6}
}

func (x *ScaleClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaleClusterRequest) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

type ScaleClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shards        int32                  `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleClusterResponse) Reset() {
	*x = ScaleClusterResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleClusterResponse) ProtoMessage() {}

func (x *ScaleClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleClusterResponse.ProtoReflect.Descriptor instead.
func (*ScaleClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{7}
}

func (x *ScaleClusterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaleClusterResponse) GetShards() int32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *ScaleClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{8}
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{9}
}

func (x *ListClustersResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type DiagnoseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnoseRequest) Reset() {
	*x = DiagnoseRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseRequest) ProtoMessage() {}

func (x *DiagnoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnoseRequest.ProtoReflect.Descriptor instead.
func (*DiagnoseRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{10}
}

func (x *DiagnoseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiagnoseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Issues        []string               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnoseResponse) Reset() {
	*x = DiagnoseResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnoseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseResponse) ProtoMessage() {}

func (x *DiagnoseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnoseResponse.ProtoReflect.Descriptor instead.
func (*DiagnoseResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{11}
}

func (x *DiagnoseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiagnoseResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DiagnoseResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *DiagnoseResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_proto_rediscluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{13}
}

func (x *EventInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventInfo           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventsResponse) GetEvents() []*EventInfo {
	if x != nil {
		return x.Events
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_rediscluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{15}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_rediscluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rediscluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_rediscluster_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_rediscluster_proto protoreflect.FileDescriptor

const file_proto_rediscluster_proto_rawDesc = "" +
	"\n" +
	"\x18proto/rediscluster.proto\x12\frediscluster\"\x9f\x01\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\x12&\n" +
	"\x0fnodes_per_shard\x18\x03 \x01(\x05R\rnodesPerShard\x12\x1d\n" +
	"\n" +
	"redis_port\x18\x04 \x01(\rR\tredisPort\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"_\n" +
	"\x15CreateClusterResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"t\n" +
	"\x0eCreateProgress\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x05R\tcompleted\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"&\n" +
	"\x10GetStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd2\x01\n" +
	"\x11GetStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12!\n" +
	"\fmaster_count\x18\x03 \x01(\x05R\vmasterCount\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12!\n" +
	"\fslot_balance\x18\x05 \x01(\tR\vslotBalance\x12,\n" +
	"\x05nodes\x18\x06 \x03(\v2\x16.rediscluster.NodeInfoR\x05nodes\"\x9f\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tmaster_id\x18\x05 \x01(\tR\bmasterId\x12\x14\n" +
	"\x05slots\x18\x06 \x03(\tR\x05slots\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\"A\n" +
	"\x13ScaleClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\"\\\n" +
	"\x14ScaleClusterResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\x05R\x06shards\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x15\n" +
	"\x13ListClustersRequest\",\n" +
	"\x14ListClustersResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"%\n" +
	"\x0fDiagnoseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"v\n" +
	"\x10DiagnoseResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06issues\x18\x03 \x03(\tR\x06issues\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\"&\n" +
	"\x10GetEventsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"o\n" +
	"\tEventInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"D\n" +
	"\x11GetEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.rediscluster.EventInfoR\x06events\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xaa\x05\n" +
	"\x13RedisClusterService\x12X\n" +
	"\rCreateCluster\x12\".rediscluster.CreateClusterRequest\x1a#.rediscluster.CreateClusterResponse\x12_\n" +
	"\x19CreateClusterWithProgress\x12\".rediscluster.CreateClusterRequest\x1a\x1c.rediscluster.CreateProgress0\x01\x12L\n" +
	"\tGetStatus\x12\x1e.rediscluster.GetStatusRequest\x1a\x1f.rediscluster.GetStatusResponse\x12U\n" +
	"\fScaleCluster\x12!.rediscluster.ScaleClusterRequest\x1a\".rediscluster.ScaleClusterResponse\x12U\n" +
	"\fListClusters\x12!.rediscluster.ListClustersRequest\x1a\".rediscluster.ListClustersResponse\x12I\n" +
	"\bDiagnose\x12\x1d.rediscluster.DiagnoseRequest\x1a\x1e.rediscluster.DiagnoseResponse\x12L\n" +
	"\tGetEvents\x12\x1e.rediscluster.GetEventsRequest\x1a\x1f.rediscluster.GetEventsResponse\x12C\n" +
	"\x06Health\x12\x1b.rediscluster.HealthRequest\x1a\x1c.rediscluster.HealthResponseB!Z\x1fredisClusterManager/proto;protob\x06proto3"

var (
	file_proto_rediscluster_proto_rawDescOnce sync.Once
	file_proto_rediscluster_proto_rawDescData []byte
)

func file_proto_rediscluster_proto_rawDescGZIP() []byte {
	file_proto_rediscluster_proto_rawDescOnce.Do(func() {
		file_proto_rediscluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rediscluster_proto_rawDesc), len(file_proto_rediscluster_proto_rawDesc)))
	})
	return file_proto_rediscluster_proto_rawDescData
}

var file_proto_rediscluster_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_rediscluster_proto_goTypes = []any{
	(*CreateClusterRequest)(nil),  // 0: rediscluster.CreateClusterRequest
	(*CreateClusterResponse)(nil), // 1: rediscluster.CreateClusterResponse
	(*CreateProgress)(nil),        // 2: rediscluster.CreateProgress
	(*GetStatusRequest)(nil),      // 3: rediscluster.GetStatusRequest
	(*GetStatusResponse)(nil),     // 4: rediscluster.GetStatusResponse
	(*NodeInfo)(nil),              // 5: rediscluster.NodeInfo
	(*ScaleClusterRequest)(nil),   // 6: rediscluster.ScaleClusterRequest
	(*ScaleClusterResponse)(nil),  // 7: rediscluster.ScaleClusterResponse
	(*ListClustersRequest)(nil),   // 8: rediscluster.ListClustersRequest
	(*ListClustersResponse)(nil),  // 9: rediscluster.ListClustersResponse
	(*DiagnoseRequest)(nil),       // 10: rediscluster.DiagnoseRequest
	(*DiagnoseResponse)(nil),      // 11: rediscluster.DiagnoseResponse
	(*GetEventsRequest)(nil),      // 12: rediscluster.GetEventsRequest
	(*EventInfo)(nil),             // 13: rediscluster.EventInfo
	(*GetEventsResponse)(nil),     // 14: rediscluster.GetEventsResponse
	(*HealthRequest)(nil),         // 15: rediscluster.HealthRequest
	(*HealthResponse)(nil),        // 16: rediscluster.HealthResponse
}
var file_proto_rediscluster_proto_depIdxs = []int32{
	5,  // 0: rediscluster.GetStatusResponse.nodes:type_name -> rediscluster.NodeInfo
	13, // 1: rediscluster.GetEventsResponse.events:type_name -> rediscluster.EventInfo
	0,  // 2: rediscluster.RedisClusterService.CreateCluster:input_type -> rediscluster.CreateClusterRequest
	0,  // 3: rediscluster.RedisClusterService.CreateClusterWithProgress:input_type -> rediscluster.CreateClusterRequest
	3,  // 4: rediscluster.RedisClusterService.GetStatus:input_type -> rediscluster.GetStatusRequest
	6,  // 5: rediscluster.RedisClusterService.ScaleCluster:input_type -> rediscluster.ScaleClusterRequest
	8,  // 6: rediscluster.RedisClusterService.ListClusters:input_type -> rediscluster.ListClustersRequest
	10, // 7: rediscluster.RedisClusterService.Diagnose:input_type -> rediscluster.DiagnoseRequest
	12, // 8: rediscluster.RedisClusterService.GetEvents:input_type -> rediscluster.GetEventsRequest
	15, // 9: rediscluster.RedisClusterService.Health:input_type -> rediscluster.HealthRequest
	1,  // 10: rediscluster.RedisClusterService.CreateCluster:output_type -> rediscluster.CreateClusterResponse
	2,  // 11: rediscluster.RedisClusterService.CreateClusterWithProgress:output_type -> rediscluster.CreateProgress
	4,  // 12: rediscluster.RedisClusterService.GetStatus:output_type -> rediscluster.GetStatusResponse
	7,  // 13: rediscluster.RedisClusterService.ScaleCluster:output_type -> rediscluster.ScaleClusterResponse
	9,  // 14: rediscluster.RedisClusterService.ListClusters:output_type -> rediscluster.ListClustersResponse
	11, // 15: rediscluster.RedisClusterService.Diagnose:output_type -> rediscluster.DiagnoseResponse
	14, // 16: rediscluster.RedisClusterService.GetEvents:output_type -> rediscluster.GetEventsResponse
	16, // 17: rediscluster.RedisClusterService.Health:output_type -> rediscluster.HealthResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rediscluster_proto_init() }
func file_proto_rediscluster_proto_init() {
	if File_proto_rediscluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rediscluster_proto_rawDesc), len(file_proto_rediscluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rediscluster_proto_goTypes,
		DependencyIndexes: file_proto_rediscluster_proto_depIdxs,
		MessageInfos:      file_proto_rediscluster_proto_msgTypes,
	}.Build()
	File_proto_rediscluster_proto = out.File
	file_proto_rediscluster_proto_goTypes = nil
	file_proto_rediscluster_proto_depIdxs = nil
}
