# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import rediscluster_pb2 as proto_dot_rediscluster__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/rediscluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RedisClusterServiceStub(object):
    """── Cluster Service ──

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCluster = channel.unary_unary(
                '/rediscluster.RedisClusterService/CreateCluster',
                request_serializer=proto_dot_rediscluster__pb2.CreateClusterRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.CreateClusterResponse.FromString,
                _registered_method=True)
        self.CreateClusterWithProgress = channel.unary_stream(
                '/rediscluster.RedisClusterService/CreateClusterWithProgress',
                request_serializer=proto_dot_rediscluster__pb2.CreateClusterRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.CreateProgress.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rediscluster.RedisClusterService/GetStatus',
                request_serializer=proto_dot_rediscluster__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.ScaleCluster = channel.unary_unary(
                '/rediscluster.RedisClusterService/ScaleCluster',
                request_serializer=proto_dot_rediscluster__pb2.ScaleClusterRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.ScaleClusterResponse.FromString,
                _registered_method=True)
        self.ListClusters = channel.unary_unary(
                '/rediscluster.RedisClusterService/ListClusters',
                request_serializer=proto_dot_rediscluster__pb2.ListClustersRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.ListClustersResponse.FromString,
                _registered_method=True)
        self.Diagnose = channel.unary_unary(
                '/rediscluster.RedisClusterService/Diagnose',
                request_serializer=proto_dot_rediscluster__pb2.DiagnoseRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.DiagnoseResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/rediscluster.RedisClusterService/GetEvents',
                request_serializer=proto_dot_rediscluster__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.GetEventsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/rediscluster.RedisClusterService/Health',
                request_serializer=proto_dot_rediscluster__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_rediscluster__pb2.HealthResponse.FromString,
                _registered_method=True)


class RedisClusterServiceServicer(object):
    """── Cluster Service ──

    """

    def CreateCluster(self, request, context):
        """Create a new Redis cluster (returns after complete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClusterWithProgress(self, request, context):
        """Create a new Redis cluster with streaming progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get cluster status and topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScaleCluster(self, request, context):
        """Scale cluster by changing shard count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClusters(self, request, context):
        """List all Redis clusters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diagnose(self, request, context):
        """Run diagnostics on a cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Get K8s events for a cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedisClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCluster,
                    request_deserializer=proto_dot_rediscluster__pb2.CreateClusterRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.CreateClusterResponse.SerializeToString,
            ),
            'CreateClusterWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateClusterWithProgress,
                    request_deserializer=proto_dot_rediscluster__pb2.CreateClusterRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.CreateProgress.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=proto_dot_rediscluster__pb2.GetStatusRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.GetStatusResponse.SerializeToString,
            ),
            'ScaleCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleCluster,
                    request_deserializer=proto_dot_rediscluster__pb2.ScaleClusterRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.ScaleClusterResponse.SerializeToString,
            ),
            'ListClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusters,
                    request_deserializer=proto_dot_rediscluster__pb2.ListClustersRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.ListClustersResponse.SerializeToString,
            ),
            'Diagnose': grpc.unary_unary_rpc_method_handler(
                    servicer.Diagnose,
                    request_deserializer=proto_dot_rediscluster__pb2.DiagnoseRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.DiagnoseResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=proto_dot_rediscluster__pb2.GetEventsRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.GetEventsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_rediscluster__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_rediscluster__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rediscluster.RedisClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rediscluster.RedisClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RedisClusterService(object):
    """── Cluster Service ──

    """

    @staticmethod
    def CreateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/CreateCluster',
            proto_dot_rediscluster__pb2.CreateClusterRequest.SerializeToString,
            proto_dot_rediscluster__pb2.CreateClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateClusterWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rediscluster.RedisClusterService/CreateClusterWithProgress',
            proto_dot_rediscluster__pb2.CreateClusterRequest.SerializeToString,
            proto_dot_rediscluster__pb2.CreateProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/GetStatus',
            proto_dot_rediscluster__pb2.GetStatusRequest.SerializeToString,
            proto_dot_rediscluster__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScaleCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/ScaleCluster',
            proto_dot_rediscluster__pb2.ScaleClusterRequest.SerializeToString,
            proto_dot_rediscluster__pb2.ScaleClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/ListClusters',
            proto_dot_rediscluster__pb2.ListClustersRequest.SerializeToString,
            proto_dot_rediscluster__pb2.ListClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diagnose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/Diagnose',
            proto_dot_rediscluster__pb2.DiagnoseRequest.SerializeToString,
            proto_dot_rediscluster__pb2.DiagnoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/GetEvents',
            proto_dot_rediscluster__pb2.GetEventsRequest.SerializeToString,
            proto_dot_rediscluster__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rediscluster.RedisClusterService/Health',
            proto_dot_rediscluster__pb2.HealthRequest.SerializeToString,
            proto_dot_rediscluster__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
