backend: "k8s"
db_path: ""
containerd_socket: ""

paths:
  redis_host_config_path: "setup/redis/config"
  redis_config_path: "/data/redis/config"
  redis_host_data_path: "setup/redis/data"
  redis_config_data_path: "/data/redis/data"
  runtime_state_dir: "runtime"

kubernetes:
  kube_config_path: ""
  namespace: "default"
  base_node_port: 30000

configs:
  save_file_name: "run_time_config.yaml"
  container_info_file_name: "containers.json"
  image_name: "redis:7-alpine"
  redis_port: 6379
