// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/rediscluster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisClusterService_CreateCluster_FullMethodName             = "/rediscluster.RedisClusterService/CreateCluster"
	RedisClusterService_CreateClusterWithProgress_FullMethodName = "/rediscluster.RedisClusterService/CreateClusterWithProgress"
	RedisClusterService_GetStatus_FullMethodName                 = "/rediscluster.RedisClusterService/GetStatus"
	RedisClusterService_ScaleCluster_FullMethodName              = "/rediscluster.RedisClusterService/ScaleCluster"
	RedisClusterService_ListClusters_FullMethodName              = "/rediscluster.RedisClusterService/ListClusters"
	RedisClusterService_Diagnose_FullMethodName                  = "/rediscluster.RedisClusterService/Diagnose"
	RedisClusterService_GetEvents_FullMethodName                 = "/rediscluster.RedisClusterService/GetEvents"
	RedisClusterService_Health_FullMethodName                    = "/rediscluster.RedisClusterService/Health"
)

// RedisClusterServiceClient is the client API for RedisClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisClusterServiceClient interface {
	// Create a new Redis cluster (returns after complete)
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
	// Create a new Redis cluster with streaming progress updates
	CreateClusterWithProgress(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateProgress], error)
	// Get cluster status and topology
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Scale cluster by changing shard count
	ScaleCluster(ctx context.Context, in *ScaleClusterRequest, opts ...grpc.CallOption) (*ScaleClusterResponse, error)
	// List all Redis clusters
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
	// Run diagnostics on a cluster
	Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error)
	// Get K8s events for a cluster
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type redisClusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisClusterServiceClient(cc grpc.ClientConnInterface) RedisClusterServiceClient {
	return &redisClusterServiceClient{cc}
}

func (c *redisClusterServiceClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClusterResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_CreateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) CreateClusterWithProgress(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RedisClusterService_ServiceDesc.Streams[0], RedisClusterService_CreateClusterWithProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateClusterRequest, CreateProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedisClusterService_CreateClusterWithProgressClient = grpc.ServerStreamingClient[CreateProgress]

func (c *redisClusterServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) ScaleCluster(ctx context.Context, in *ScaleClusterRequest, opts ...grpc.CallOption) (*ScaleClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleClusterResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_ScaleCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_ListClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnoseResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_Diagnose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClusterServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RedisClusterService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisClusterServiceServer is the server API for RedisClusterService service.
// All implementations must embed UnimplementedRedisClusterServiceServer
// for forward compatibility.
type RedisClusterServiceServer interface {
	// Create a new Redis cluster (returns after complete)
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	// Create a new Redis cluster with streaming progress updates
	CreateClusterWithProgress(*CreateClusterRequest, grpc.ServerStreamingServer[CreateProgress]) error
	// Get cluster status and topology
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Scale cluster by changing shard count
	ScaleCluster(context.Context, *ScaleClusterRequest) (*ScaleClusterResponse, error)
	// List all Redis clusters
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	// Run diagnostics on a cluster
	Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error)
	// Get K8s events for a cluster
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRedisClusterServiceServer()
}

// UnimplementedRedisClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisClusterServiceServer struct{}

func (UnimplementedRedisClusterServiceServer) CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCluster not implemented")
}
func (UnimplementedRedisClusterServiceServer) CreateClusterWithProgress(*CreateClusterRequest, grpc.ServerStreamingServer[CreateProgress]) error {
	return status.Error(codes.Unimplemented, "method CreateClusterWithProgress not implemented")
}
func (UnimplementedRedisClusterServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRedisClusterServiceServer) ScaleCluster(context.Context, *ScaleClusterRequest) (*ScaleClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleCluster not implemented")
}
func (UnimplementedRedisClusterServiceServer) ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusters not implemented")
}
func (UnimplementedRedisClusterServiceServer) Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diagnose not implemented")
}
func (UnimplementedRedisClusterServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedRedisClusterServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRedisClusterServiceServer) mustEmbedUnimplementedRedisClusterServiceServer() {}
func (UnimplementedRedisClusterServiceServer) testEmbeddedByValue()                             {}

// UnsafeRedisClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisClusterServiceServer will
// result in compilation errors.
type UnsafeRedisClusterServiceServer interface {
	mustEmbedUnimplementedRedisClusterServiceServer()
}

func RegisterRedisClusterServiceServer(s grpc.ServiceRegistrar, srv RedisClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedRedisClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisClusterService_ServiceDesc, srv)
}

func _RedisClusterService_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_CreateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_CreateClusterWithProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RedisClusterServiceServer).CreateClusterWithProgress(m, &grpc.GenericServerStream[CreateClusterRequest, CreateProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedisClusterService_CreateClusterWithProgressServer = grpc.ServerStreamingServer[CreateProgress]

func _RedisClusterService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_ScaleCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).ScaleCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_ScaleCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).ScaleCluster(ctx, req.(*ScaleClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_ListClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_Diagnose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).Diagnose(ctx, req.(*DiagnoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisClusterService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisClusterServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisClusterService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisClusterServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisClusterService_ServiceDesc is the grpc.ServiceDesc for RedisClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rediscluster.RedisClusterService",
	HandlerType: (*RedisClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCluster",
			Handler:    _RedisClusterService_CreateCluster_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RedisClusterService_GetStatus_Handler,
		},
		{
			MethodName: "ScaleCluster",
			Handler:    _RedisClusterService_ScaleCluster_Handler,
		},
		{
			MethodName: "ListClusters",
			Handler:    _RedisClusterService_ListClusters_Handler,
		},
		{
			MethodName: "Diagnose",
			Handler:    _RedisClusterService_Diagnose_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _RedisClusterService_GetEvents_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RedisClusterService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateClusterWithProgress",
			Handler:       _RedisClusterService_CreateClusterWithProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rediscluster.proto",
}
